name: Deploy App
on: [push, workflow_dispatch]
jobs:
  test-code:
    runs-on: ubuntu-latest
    steps:
      - name: copying the codes
        uses: actions/checkout@v5

      - name: install node-js
        uses: actions/setup-node@v5
        with:
          node-version: 22.21.0
      - name: check node node-version
        run: node -v
      - name: install dependencies
        run: npm install --frozen-lockfile
      - name: run tests
        run: npm run test
